name: Construire l'APK

on:
  push:
    branches: [main, master]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Construire l'APK
        run: |
          buildozer android debug

      - name: Mettre l'APK à disposition
        uses: actions/upload-artifact@v4
        with:
          name: TraitesBancaires-apk
          path: bin/*.apk
